name: Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.2"
          cabal-version: "3.12.1.0"
          cabal-update: true

      - name: Cache Cabal
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal', 'cabal.project', 'cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Compile
        run: make build

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.2"
          cabal-version: "3.12.1.0"
          cabal-update: true

      - name: Cache Cabal
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal', 'cabal.project', 'cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Test
        run: make test

  lint:
    runs-on: ubuntu-latest
    env:
      HLINT_VERSION: "3.10"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.2"
          cabal-version: "3.12.1.0"
          cabal-update: true

      - name: Cache Cabal
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal', 'cabal.project', 'cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Install HLint
        uses: haskell-actions/hlint-setup@v2
        with:
          version: ${{ env.HLINT_VERSION }}

      - name: Lint
        uses: haskell-actions/hlint-run@v2
        with:
          path: '["src/", "test"]'
          fail-on: warning
